version: '3.8'

services:
  web:
    build: 
      context: ./web
    volumes:
      - ./web:/var/www/html
    ports:
      - "8080:80"
      - "8443:443"
    env_file:
      - .env
    depends_on:
      - db
      - mailcatcher
  db:
    build: ./db
    env_file:
      - .env                      
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  mailcatcher:
    image: dockage/mailcatcher
    container_name: mailcatcher
    ports:
      - "1080:1080"  # Interface web MailCatcher
      - "1025:1025"  # Port SMTP utilisé par MailCatcher
      
volumes:
  db_data: