FROM php:8.1-fpm-alpine

RUN apk add --no-cache nginx \
    && docker-php-ext-install pdo pdo_mysql

COPY ./ /var/www/html/
COPY nginx.conf /etc/nginx/nginx.conf
COPY ./certs/selfsigned.crt /etc/nginx/ssl/selfsigned.crt
COPY ./certs/selfsigned.key /etc/nginx/ssl/selfsigned.key

WORKDIR /var/www/html

EXPOSE 80 443

# Commande pour démarrer PHP-FPM et Nginx ensemble
CMD ["sh", "-c", "php-fpm & nginx -g 'daemon off;'"]
