FROM php:8.1-fpm-alpine

RUN apk add --no-cache nginx \
    && docker-php-ext-install pdo pdo_mysql

# GD library for superimpose two picture
RUN apk --no-cache add \
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    libwebp-dev \
    libxpm-dev

RUN docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp --with-xpm && docker-php-ext-install gd

COPY ./ /var/www/html/
COPY nginx.conf /etc/nginx/nginx.conf
COPY ./certs/selfsigned.crt /etc/nginx/ssl/selfsigned.crt
COPY ./certs/selfsigned.key /etc/nginx/ssl/selfsigned.key

WORKDIR /var/www/html

EXPOSE 80 443

# Commande pour démarrer PHP-FPM et Nginx ensemble
CMD ["sh", "-c", "php-fpm & nginx -g 'daemon off;'"]
