FROM php:8.1-fpm-alpine

RUN apk add --no-cache nginx \
    && docker-php-ext-install pdo pdo_mysql

RUN apk --no-cache add \
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    libwebp-dev \
    libxpm-dev

RUN docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp --with-xpm && docker-php-ext-install gd

COPY ./ /var/www/html/
COPY nginx.conf /etc/nginx/nginx.conf                                                                                                                                                                                                                                                                                                                                                                                                                        
COPY ./certs/selfsigned.crt /etc/nginx/ssl/selfsigned.crt
COPY ./certs/selfsigned.key /etc/nginx/ssl/selfsigned.key
COPY php.ini /usr/local/etc/php/conf.d/
RUN mkdir -p /var/log && touch /var/log/php_errors.log && chmod 777 /var/log/php_errors.log

WORKDIR /var/www/html

EXPOSE 80 443

CMD ["sh", "-c", "php-fpm & nginx -g 'daemon off;'"]


